### PR TITLE
Fix Rosalina menu

### PR DESCRIPTION
**Pull request by HIDE810**
With this fix, the credit menu will be displayed.

### CODE REVIEW

**Comment by jbmagination** [comment]
Would like to confirm that this adds the menu back, albeit it's not a requirement to add. Until it gets added, I have a fork with a compiled download of this patch.

**Comment by jbmagination** [comment]
PLEASE ADD THIS

**Comment by jbmagination** [comment]
How is this request still open

**Comment by HIDE810** [comment]
This repository hasn't been updated for a long while. I'll close this.

**Comment by jbmagination** [comment]
On we go with our own fork then.

**Pull request closed without merging**
